spring:
  kafka:
    consumer:
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
          deserializer:
            key:
              delegate: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate: org.springframework.kafka.support.serializer.JsonDeserializer
          json:
            trusted:
              packages: "*"
